export class DatosEmpresa {
    id:number;
    tipoEmpresa:string;
    numeroEmpresa:number;
    nombreEmpresa:string;
    direccionEmpresa:string;
    paisEmpresa:string;
    departamentoEmpresa:string;
    ciudadEmpresa:string;
    telefonoEmpresa:number;
    tipoResponsable:string;
    numeroResponsable:number;
    nombreResponsable:string;
    direccionResponsable:string;
    telefonoesponsable:string;
    paisresponsable:string;
    departamentoresponsable:string;
    ciudadResponsable:string;
}
